export const queryKeys = {
  opportunities: (baseUrl) => ["opportunities", "all", baseUrl],
  courses: (baseUrl) => ["courses", "all", baseUrl],
  course: (baseUrl, courseId) => ["courses", "detail", baseUrl, String(courseId)],
  verifyStudent: (baseUrl, courseId, token) => [
    "courses",
    "verify-student",
    baseUrl,
    String(courseId),
    token,
  ],
  recordings: (baseUrl, courseId, token) => [
    "courses",
    "recordings",
    baseUrl,
    String(courseId),
    token,
  ],
  resources: (baseUrl, courseId, token) => [
    "courses",
    "resources",
    baseUrl,
    String(courseId),
    token,
  ],
  currentUser: (baseUrl, token) => ["users", "current", baseUrl, token],
  userCourses: (baseUrl, token) => ["users", "courses", baseUrl, token],
  userDocRequests: (baseUrl, token) => ["users", "doc-requests", baseUrl, token],
  userVisaRequests: (baseUrl, token) => ["users", "visa-requests", baseUrl, token],
  docRequest: (baseUrl, token, requestId) => [
    "doc-requests",
    "detail",
    baseUrl,
    token,
    String(requestId),
  ],
  docRequestNotes: (baseUrl, token, requestId) => [
    "doc-requests",
    "notes",
    baseUrl,
    token,
    String(requestId),
  ],
  adminDocRequests: (baseUrl, token) => ["admin", "doc-requests", baseUrl, token],
  adminDocRequest: (baseUrl, token, requestId) => [
    "admin",
    "doc-request",
    baseUrl,
    token,
    String(requestId),
  ],
  allUsers: (baseUrl, token) => ["admin", "users", "all", baseUrl, token],
  learners: (baseUrl, courseId, token) => [
    "courses",
    "learners",
    baseUrl,
    String(courseId),
    token,
  ],
  joinRequests: (baseUrl, courseId, token) => [
    "courses",
    "join-requests",
    baseUrl,
    String(courseId),
    token,
  ],
};
